service: python-${opt:stackName}

provider:
  name: aws
  runtime: python3.7
  region: eu-west-2

functions:
  hello:
    handler: src/hello.hello
    events:
      - http:
          method: GET
          path: hello

  sum:
    handler: src/sum.sum
    events:
      - http:
          method: POST
          path: sum
