version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4-node
    working_directory: ~/python
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            yarn
            pipenv install --dev
      - run:
          name: Run Behave tests
          command: |
            chmod +x ci-behave.sh
            ./ci-behave.sh


